### ISSUE TITLE
Doesn't Generate A Project - Package Template In Jar

### ISSUE THREAD

**Issue by opticyclic** [janisolekss/cordagen#3]
This doesn't actually generate a project:

    ./gradlew build
    mkdir /tmp/test
    cp build/libs/cordagen-0.1.jar /tmp/test
    cd /tmp/test
    java -cp cordagen-0.1.jar com.cordagen.MainKt role role_name project_name
    Making module direcotry role_name
    Creating module source direcotry
    Creating module test direcotry
    Copying build.gradle
    Exception in thread "main" kotlin.io.NoSuchFileException: ./templates/role_build.gradle_: The source file doesn't exist.
            at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:186)
            at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:184)
            at com.cordagen.MainKt.copyGradle(Main.kt:139)
            at com.cordagen.MainKt.doRoleGen(Main.kt:102)
            at com.cordagen.MainKt.doCommand(Main.kt:58)
            at com.cordagen.MainKt.main(Main.kt:31)

You should package up the template in the jar and generate a new project on disk instead of modifying the source code from this project.

**Comment by janisolekss** [comment]
This is by design. Project is self-modifying.

**Comment by opticyclic** [comment]
A better design would be to generate on a copy of the source instead of directly on the source of this project.
That way you can run the project multiple times and check that you are generating correctly without having git changes in your working copy.

The current design is not clear in the README and as it is not usual behaviour to modify the contents of the source code maybe you should update the README to be explicit about the unusual way that this "generator" works.
